namespace Vitraux.JsCodeGeneration.QueryElements.OneTimeOnDemand;

internal interface IQueryElementsDeclaringOneTimeOnDemandByQuerySelectorJsCodeGenerator : IQueryElementsDeclaringJsCodeGenerator { }
