namespace Vitraux.JsCodeGeneration.QueryElements.Strategies.OneTimeOnDemand;

internal interface IJsQueryFromTemplateElementsDeclaringOneTimeOnDemandGeneratorFactory
    : IJsQueryFromTemplateElementsDeclaringGeneratorFactory
{
}