namespace Vitraux.JsCodeGeneration.QueryElements.Strategies.OneTimeOnDemand;

internal interface IQueryElementsDeclaringOneTimeOnDemandByQuerySelectorJsCodeGenerator : IQueryElementsDeclaringJsCodeGenerator { }
