namespace Vitraux.JsCodeGeneration.QueryElements.Strategies.OneTimeOnDemand;

internal interface IQueryElementsDeclaringOneTimeOnDemandByIdJsCodeGenerator : IQueryElementsDeclaringJsCodeGenerator { }
