namespace Vitraux.JsCodeGeneration.QueryElements.Strategies.OneTimeOnDemand;

internal interface IQueryElementsDeclaringOneTimeOnDemandByTemplateJsCodeGenerator : IQueryElementsDeclaringJsCodeGenerator { }
