using Vitraux;

namespace Rucula.Presentation.Mappings;

internal sealed class ConfigurationBehaviorProvider : IConfigurationBehaviorProvider
{
    public ConfigurationBehavior DefaultConfigurationBehavior { get; } = new()
    {
        ActionRegistrationStrategy = ActionRegistrationStrategy.OnlyOnceAtStart,
        AutoGeneratedFunctionCaching = AutoGeneratedFunctionCaching.ByVersion("v1.4"),
        QueryElementStrategy = QueryElementStrategy.OnlyOnceAtStart,
        TrackChanges = true
    };
}
