using Rucula.Presentation.ActionBinders;
using Rucula.Presentation.ViewModels;
using Vitraux;

namespace Rucula.Presentation.Mappings;

internal sealed class RuculaScreenConfigurationMapping : IViewModelConfiguration<RuculaScreenViewModel>
{
    public ConfigurationBehavior ConfigurationBehavior { get; } = new()
    {
        ActionRegistrationStrategy = ActionRegistrationStrategy.OnlyOnceAtStart,
        AutoGeneratedFunctionCaching = AutoGeneratedFunctionCaching.ByVersion("v1"),
        QueryElementStrategy = QueryElementStrategy.OnlyOnceAtStart,
        TrackChanges = true
    };

    public ModelMappingData ConfigureMapping(IModelMapper<RuculaScreenViewModel> modelMapper)
        => modelMapper
            .MapActionAsync<IRuculaScreenRefreshActionBinderAsync>().FromInputs.ById("refresh-button").On("click").AddRuculaParameters()
            .MapActionAsync<IRuculaScreenRecalculateActionBinderAsync>().FromInputs.ByQuery("[data-recalculate]").On("click").AddRuculaParameters()
            .MapValue(ci => ci.IsRunning)
                .ToElements.ByQuery("[data-disabled-when-running]").ToAttribute("disabled")
                .ToElements.ById("loading-indicator").ToAttribute("data-inline-block")
            .MapValue(ci => !ci.IsRunning)
                .ToElements.ById("all-indicators-container").ToAttribute("data-hidden")
                .ToElements.ById("winning-choice").ToAttribute("data-inline-block")
            .Data;
}
