using Rucula.Presentation.ViewModels;
using Vitraux;

namespace Rucula.Presentation.Mappings;

internal class WinningChoiceConfigurationMapping(ISpanishPriceFormatProvider spanishPriceFormatter) : IViewModelConfiguration<WinningChoiceViewModel>
{
    public ConfigurationBehavior ConfigurationBehavior { get; } = new()
    {
        ActionRegistrationStrategy = ActionRegistrationStrategy.OnlyOnceAtStart,
        AutoGeneratedFunctionCaching = AutoGeneratedFunctionCaching.ByVersion("v1"),
        QueryElementStrategy = QueryElementStrategy.OnlyOnceAtStart,
        TrackChanges = true
    };

    public ModelMappingData ConfigureMapping(IModelMapper<WinningChoiceViewModel> modelMapper)
        => modelMapper
            .MapValue(w => w.Name).ToElements.ById("winner-name").ToContent
            .MapValue(w => FormatDolarPrice(w.DolarPrice)).ToElements.ById("winner-name").ToContent
            .Data;

    private string FormatDolarPrice(double? dolarPrice)
        => dolarPrice?.ToString(spanishPriceFormatter) ?? string.Empty;
}
